import { useEffect, useRef, useState } from "react";
import * as api from "./api";
import type { AdminUser, AuthUser, Role } from "./api";

const roles: Role[]=["REQUESTER","IT_STAFF","ADMINISTRATOR"];
const roleText=(r:Role)=>r==="IT_STAFF"?"IT Staff":r==="ADMINISTRATOR"?"Administrator":"Requester";
export function UserManagementScreen({currentUser,onReauthentication}:{currentUser:AuthUser;onReauthentication:(message:string)=>void}){
 const [users,setUsers]=useState<AdminUser[]>([]),[search,setSearch]=useState(""),[role,setRole]=useState<Role|"">("");
 const [state,setState]=useState<"loading"|"ready"|"error">("loading"),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 const [mode,setMode]=useState<"create"|"edit"|null>(null),[selected,setSelected]=useState<AdminUser|null>(null),[busy,setBusy]=useState(false),[confirmActivation,setConfirmActivation]=useState(false),[resetOpen,setResetOpen]=useState(false);
 const [name,setName]=useState(""),[email,setEmail]=useState(""),[editRole,setEditRole]=useState<Role>("REQUESTER"),[active,setActive]=useState(true),[password,setPassword]=useState("");
 const firstRef=useRef<HTMLInputElement>(null);
 const load=async()=>{setState("loading");setError(null);try{const r=await api.getAdminUsers({search,role:role||null});setUsers(r.items);setState("ready");}catch(e){setState("error");setError((e as Error).message);}};
 useEffect(()=>{void load();},[search,role]);
 const openCreate=()=>{setMode("create");setSelected(null);setName("");setEmail("");setEditRole("REQUESTER");setActive(true);setPassword("");setNotice(null);setTimeout(()=>firstRef.current?.focus(),0);};
 const openEdit=(u:AdminUser)=>{setMode("edit");setSelected(u);setName(u.name);setEmail(u.email);setEditRole(u.role);setActive(u.isActive);setPassword("");setNotice(null);setTimeout(()=>firstRef.current?.focus(),0);};
 const save=async()=>{setError(null);setNotice(null); if(!name.trim()){setError("Name is required.");firstRef.current?.focus();return;} if(!email.includes("@")){setError("Enter a valid email address.");return;} if(mode==="create"&&!password){setError("Initial Password is required.");return;} if(mode==="edit"&&selected&&selected.isActive!==active&&!confirmActivation){setConfirmActivation(true);return;} setBusy(true);try{const result=mode==="create"?await api.createAdminUser({name,email,role:editRole,isActive:active,initialPassword:password}):await api.updateAdminUser(selected!.id,{name,email,role:editRole,isActive:active,expectedVersion:selected!.version});setPassword("");setConfirmActivation(false); if("reauthenticationRequired" in result&&result.reauthenticationRequired){onReauthentication("Your account was updated. Sign in again.");return;} setNotice(mode==="create"?"User created. Give the initial password to the user manually.":"User account updated.");setMode(null);setSelected(null);await load();}catch(e:any){setError(e.code==="EMAIL_CONFLICT"?"That email address is already in use, including inactive accounts.":e.code==="VERSION_CONFLICT"?"This account changed. Refresh and review before retrying.":e.code==="LAST_ACTIVE_ADMIN"?"At least one active Administrator must remain.":e.code==="ADMIN_SELF_DEACTIVATION"?"You cannot deactivate your own Administrator account.":e.message);}finally{setBusy(false);}};
 const reset=async()=>{if(!selected||!password)return;setBusy(true);setError(null);try{const result=await api.resetAdminInitialPassword(selected.id,{initialPassword:password,expectedVersion:selected.version});setPassword("");setResetOpen(false);if(result.reauthenticationRequired){onReauthentication("Your initial password was reset. Sign in and change it before continuing.");return;}setNotice("Initial password reset. Give the new initial password to the user manually.");setSelected(result.user);await load();}catch(e:any){setError(e.code==="VERSION_CONFLICT"?"This account changed. Refresh and review before retrying.":e.message);}finally{setBusy(false);}};
 return <main className="shell-content admin-users-page" aria-busy={state==="loading"||busy}><div className="page-heading"><div><p className="eyebrow">Administrator workspace</p><h1>User Management</h1><p>Create and maintain one-role accounts. Deactivate accounts instead of deleting them.</p></div><button className="button" onClick={openCreate}>Create User</button></div>
 {notice&&<div className="alert alert-success" role="status">{notice}</div>}{error&&<div className="alert alert-error" role="alert">{error}{state==="error"&&<button className="button button-secondary retry-button" onClick={load}>Retry</button>}</div>}
 <section className="detail-card"><div className="admin-filter-grid"><label>Search name or email<input value={search} maxLength={120} onChange={e=>setSearch(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as Role|"")}><option value="">All Roles</option>{roles.map(r=><option key={r} value={r}>{roleText(r)}</option>)}</select></label></div></section>
 {state==="loading"?<p role="status">Loading users…</p>:state==="ready"&&users.length===0?<div className="empty-state"><h2>{search||role?"No matching users":"No users"}</h2><p>{search||role?"Clear the search or role filter to see other accounts.":"Create the first account."}</p></div>:state==="ready"&&<><div className="admin-user-table-wrap"><table className="tickets-table admin-user-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td><span className="badge">{roleText(u.role)}</span></td><td><span className="badge">{u.isActive?"Active":"Inactive"}</span></td><td><button className="button button-secondary" onClick={()=>openEdit(u)}>Edit {u.name}</button></td></tr>)}</tbody></table></div><div className="admin-user-cards">{users.map(u=><article className="ticket-card" key={u.id}><h2>{u.name}</h2><p>{u.email}</p><p><strong>Role:</strong> {roleText(u.role)}</p><p><strong>Status:</strong> {u.isActive?"Active":"Inactive"}</p><button className="button button-secondary" onClick={()=>openEdit(u)}>Edit {u.name}</button></article>)}</div></>}
 {mode&&<section className="detail-card admin-editor" aria-labelledby="admin-editor-heading"><h2 id="admin-editor-heading">{mode==="create"?"Create User":`Edit ${selected?.name}`}</h2><label>Name<input ref={firstRef} value={name} maxLength={120} onChange={e=>setName(e.target.value)} disabled={busy}/></label><label>Email<input type="email" value={email} maxLength={254} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><label>Role<select value={editRole} onChange={e=>setEditRole(e.target.value as Role)} disabled={busy}>{roles.map(r=><option key={r} value={r}>{roleText(r)}</option>)}</select></label><label className="checkbox-row"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} disabled={busy||(mode==="edit"&&selected?.id===currentUser.id&&selected.role==="ADMINISTRATOR")}/> Active account</label>{mode==="edit"&&selected?.id===currentUser.id&&<p className="hint">You cannot deactivate your own Administrator account.</p>}{mode==="create"&&<><label>Initial Password<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/></label><p className="hint">15-128 characters; spaces and Unicode allowed; maximum 512 UTF-8 bytes.</p></>}<div className="button-row"><button className="button" disabled={busy} onClick={save}>{busy?"Saving…":"Save User"}</button><button className="button button-secondary" disabled={busy} onClick={()=>{setMode(null);setPassword("");}}>Cancel</button>{mode==="edit"&&<button className="button button-secondary" disabled={busy} onClick={()=>{setResetOpen(true);setPassword("");}}>Set New Initial Password</button>}</div></section>}
 {confirmActivation&&<div className="dialog-backdrop"><div role="dialog" aria-modal="true" aria-labelledby="activation-confirm"><h2 id="activation-confirm">Confirm activation change</h2><p>{active?"Activate":"Deactivate"} this account? Active sessions will be revoked and owner eligibility is rechecked.</p><button className="button" onClick={()=>{setConfirmActivation(false);void save();}}>Confirm Account Change</button><button className="button button-secondary" onClick={()=>setConfirmActivation(false)}>Cancel</button></div></div>}
 {resetOpen&&selected&&<div className="dialog-backdrop"><div role="dialog" aria-modal="true" aria-labelledby="reset-heading"><h2 id="reset-heading">Set New Initial Password</h2><p>This revokes the user's sessions and requires a password change at next login.</p><label>New Initial Password<input autoFocus type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="hint">15-128 characters; never sent by email.</p><button className="button" disabled={busy||!password} onClick={reset}>{busy?"Resetting…":"Confirm Password Reset"}</button><button className="button button-secondary" disabled={busy} onClick={()=>{setResetOpen(false);setPassword("");}}>Cancel</button></div></div>}
 </main>;
}
