import { createHash } from "node:crypto";
import request from "supertest";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { createApp } from "../../src/app.js";

const origin="http://127.0.0.1:5173", token="admin-user-test", tokenHash=createHash("sha256").update(token).digest("hex"), cookie=`toktickit.sid=${token}`, csrf="a".repeat(64);
function user(role="ADMINISTRATOR"){return {id:20,name:"Admin One",email:"admin@example.test",role,isActive:true,passwordHash:"unused",mustChangePassword:false,passwordChangedAt:new Date(),version:3,createdAt:new Date(),updatedAt:new Date()};}
function prisma(role="ADMINISTRATOR"){
 const u=user(role); const {passwordHash:_secret,...safe}=u; const requester=user("REQUESTER"); const {passwordHash:_secret2,...safeRequester}=requester; const items=[safe,{...safeRequester,id:1,name:"Alice Requester",email:"alice@example.test",version:1}];
 const tx:any={requesterUser:{findMany:vi.fn().mockResolvedValue(items),findUnique:vi.fn().mockResolvedValue(u),count:vi.fn().mockResolvedValue(2),create:vi.fn(async({data}:any)=>({...u,...data,id:30,version:1,createdAt:new Date(),updatedAt:new Date()})),updateMany:vi.fn().mockResolvedValue({count:1})},session:{deleteMany:vi.fn().mockResolvedValue({count:1})},ticket:{findMany:vi.fn().mockResolvedValue([]),update:vi.fn()},ticketOwnerChange:{create:vi.fn()},$queryRaw:vi.fn().mockResolvedValue([{locked:1}])};
 const p:any={...tx,session:{...tx.session,findUnique:vi.fn(async({where}:any)=>where.tokenHash===tokenHash?{id:"00000000-0000-4000-8000-000000000063",tokenHash,userId:u.id,csrfToken:csrf,createdAt:new Date(Date.now()-1000),lastSeenAt:new Date(),expiresAt:new Date(Date.now()+3600000),user:u}:null),update:vi.fn().mockResolvedValue({}),updateMany:vi.fn().mockResolvedValue({count:1}),deleteMany:tx.session.deleteMany},$transaction:vi.fn(async(cb:any)=>cb(tx)),category:{findMany:vi.fn()},relatedSystem:{findMany:vi.fn()},ticket:{...tx.ticket,findFirst:vi.fn(),count:vi.fn()},attachment:{},publicComment:{},internalNote:{}}; return {p,tx};
}
beforeEach(()=>{process.env.CLIENT_ORIGIN=origin;});
describe("Administrator User Management API",()=>{
 it("lists/searches users only for Administrator",async()=>{const {p}=prisma();const r=await request(createApp(p)).get("/api/admin/users?search=alice&role=REQUESTER").set("Cookie",cookie);expect(r.status).toBe(200);expect(r.body.applied).toEqual({search:"alice",role:"REQUESTER"});expect(r.body.items[0]).not.toHaveProperty("passwordHash");const denied=prisma("IT_STAFF");expect((await request(createApp(denied.p)).get("/api/admin/users").set("Cookie",cookie)).status).toBe(403);});
 it("creates a one-role account with initial-password change required",async()=>{const {p,tx}=prisma();const r=await request(createApp(p)).post("/api/admin/users").set("Cookie",cookie).set("Origin",origin).set("X-CSRF-Token",csrf).send({name:"New Staff",email:" NEW.STAFF@example.test ",role:"IT_STAFF",isActive:true,initialPassword:"valid initial password 2026"});expect(r.status).toBe(201);expect(r.body.user.email).toBe("new.staff@example.test");expect(r.body.user.mustChangePassword).toBe(true);expect(tx.requesterUser.create).toHaveBeenCalled();});
 it("rejects self-deactivation before mutation",async()=>{const {p,tx}=prisma();const r=await request(createApp(p)).patch("/api/admin/users/20").set("Cookie",cookie).set("Origin",origin).set("X-CSRF-Token",csrf).send({name:"Admin One",email:"admin@example.test",role:"ADMINISTRATOR",isActive:false,expectedVersion:3});expect(r.status).toBe(409);expect(r.body.error.code).toBe("ADMIN_SELF_DEACTIVATION");expect(tx.requesterUser.updateMany).not.toHaveBeenCalled();});
 it("rejects malformed admin queries and user deletion",async()=>{const {p}=prisma();expect((await request(createApp(p)).get("/api/admin/users?status=active").set("Cookie",cookie)).status).toBe(400);const d=await request(createApp(p)).delete("/api/admin/users/1").set("Cookie",cookie).set("Origin",origin).set("X-CSRF-Token",csrf);expect(d.status).toBe(405);});
});
