import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as api from "../../src/api";
import { UserManagementScreen } from "../../src/UserManagement";

vi.mock("../../src/api", async()=>{const actual=await vi.importActual<typeof import("../../src/api")>("../../src/api");return {...actual,getAdminUsers:vi.fn(),createAdminUser:vi.fn(),updateAdminUser:vi.fn(),resetAdminInitialPassword:vi.fn()};});
const admin={id:20,name:"Admin One",email:"admin@example.test",role:"ADMINISTRATOR",mustChangePassword:false} as const;
const row={...admin,isActive:true,version:3,passwordChangedAt:null,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z"};
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.getAdminUsers).mockResolvedValue({items:[row],applied:{search:"",role:null}});});
describe("UI-08/UI-09 User Management",()=>{
 it("lists users and exposes search, role filter and create flow",async()=>{render(<UserManagementScreen currentUser={admin} onReauthentication={vi.fn()}/>);expect((await screen.findAllByText("admin@example.test")).length).toBeGreaterThan(0);fireEvent.change(screen.getByLabelText("Search name or email"),{target:{value:"Admin"}});await waitFor(()=>expect(api.getAdminUsers).toHaveBeenLastCalledWith({search:"Admin",role:null}));fireEvent.click(screen.getByRole("button",{name:"Create User"}));expect(screen.getByRole("heading",{name:"Create User"})).toBeInTheDocument();await waitFor(()=>expect(screen.getByLabelText("Name")).toHaveFocus());});
 it("creates and clears the initial password",async()=>{vi.mocked(api.createAdminUser).mockResolvedValue({user:{...row,id:30,name:"Staff",email:"staff@example.test",role:"IT_STAFF"}});render(<UserManagementScreen currentUser={admin} onReauthentication={vi.fn()}/>);await screen.findAllByText("admin@example.test");fireEvent.click(screen.getByRole("button",{name:"Create User"}));fireEvent.change(screen.getByLabelText("Name"),{target:{value:"Staff"}});fireEvent.change(screen.getByLabelText("Email"),{target:{value:"staff@example.test"}});fireEvent.change(screen.getAllByLabelText("Role")[1],{target:{value:"IT_STAFF"}});fireEvent.change(screen.getByLabelText("Initial Password"),{target:{value:"valid initial password 2026"}});fireEvent.click(screen.getByRole("button",{name:"Save User"}));expect(await screen.findByText(/Give the initial password/)).toBeInTheDocument();expect(api.createAdminUser).toHaveBeenCalledWith(expect.objectContaining({role:"IT_STAFF"}));});
 it("disables self-deactivation and provides separate reset confirmation",async()=>{render(<UserManagementScreen currentUser={admin} onReauthentication={vi.fn()}/>);await screen.findAllByText("admin@example.test");fireEvent.click(screen.getAllByRole("button",{name:"Edit Admin One"})[0]);expect(screen.getByLabelText("Active account")).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"Set New Initial Password"}));expect(screen.getByRole("dialog",{name:"Set New Initial Password"})).toBeInTheDocument();expect(screen.getByLabelText("New Initial Password")).toHaveAttribute("type","password");});
});
