import { Prisma, type PrismaClient, type UserRole } from "@prisma/client";
import type { Express, Request, Response } from "express";
import { randomUUID } from "node:crypto";
import { hashPassword, validatePasswordInput, verifyPassword } from "./password.js";
import { clearSessionCookie, requireRequestCsrf, type AuthenticatedRequest } from "./auth.js";
import { lockAccountSafety, lockAdministratorSafety } from "./account-safety-lock.js";

export type AdminPrisma = Pick<PrismaClient, "requesterUser" | "session" | "ticket" | "ticketOwnerChange" | "$transaction" | "$queryRaw">;
const roles: UserRole[] = ["REQUESTER", "IT_STAFF", "ADMINISTRATOR"];
const adminSelect = { id:true,name:true,email:true,role:true,isActive:true,mustChangePassword:true,version:true,passwordChangedAt:true,createdAt:true,updatedAt:true } as const;

function fail(res:Response,status:number,code:string,message:string,fieldErrors?:Record<string,string[]>) { const error:any={code,message}; if(fieldErrors&&Object.keys(fieldErrors).length) error.fieldErrors=fieldErrors; if(status>=500) error.correlationId=randomUUID(); return res.status(status).json({error}); }
function admin(req:AuthenticatedRequest,res:Response){ if(req.auth?.user.role==="ADMINISTRATOR") return true; fail(res,403,"ROLE_FORBIDDEN","This account is not permitted to perform that operation."); return false; }
function positiveId(value:string){ return /^[1-9]\d*$/.test(value)&&Number.isSafeInteger(Number(value))&&Number(value)<=2147483647?Number(value):null; }
function emailValue(v:unknown){ if(typeof v!=="string") return null; const e=v.trim().toLowerCase(); return e.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)?e:null; }
function nameValue(v:unknown){ if(typeof v!=="string") return null; const n=v.trim(); return n.length>=1&&n.length<=120?n:null; }
function exactObject(body:unknown, fields:string[]){ return !!body&&typeof body==="object"&&!Array.isArray(body)&&Object.keys(body as object).length===fields.length&&fields.every(k=>Object.prototype.hasOwnProperty.call(body,k))&&Object.keys(body as object).every(k=>fields.includes(k)); }
function mapPrisma(error:unknown,res:Response){ if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002") return fail(res,409,"EMAIL_CONFLICT","That email address is already in use.",{email:["That email address is already in use."]}); if(error instanceof Error){ const known:any={VERSION_CONFLICT:[409,"VERSION_CONFLICT","This account changed. Refresh and review before retrying."],ADMIN_SELF_DEACTIVATION:[409,"ADMIN_SELF_DEACTIVATION","You cannot deactivate your own Administrator account."],LAST_ACTIVE_ADMIN:[409,"LAST_ACTIVE_ADMIN","At least one active Administrator must remain."],INITIAL_PASSWORD_SAME:[400,"VALIDATION_FAILED","The new initial password must differ from the current password."]}; if(known[error.message]) { const [status,code,message]=known[error.message] as [number,string,string]; return fail(res,status,code,message); } } return fail(res,500,"INTERNAL_ERROR","Unable to complete this request. Please try again."); }
function validateAccount(body:unknown, create:boolean){ const fields=create?["name","email","role","isActive","initialPassword"]:["name","email","role","isActive","expectedVersion"]; const errors:Record<string,string[]>={}; if(!exactObject(body,fields)) return {errors:{body:["Request body must contain exactly the documented fields."]}}; const b=body as any; const name=nameValue(b.name); const email=emailValue(b.email); if(!name) errors.name=["Name must contain 1 to 120 characters."]; if(!email) errors.email=["Enter a valid email address up to 254 characters."]; if(!roles.includes(b.role)) errors.role=["Select one permitted role."]; if(typeof b.isActive!=="boolean") errors.isActive=["Active must be a Boolean value."]; if(create){ if(typeof b.initialPassword!=="string") errors.initialPassword=["Initial password is required."]; else { const p=validatePasswordInput(b.initialPassword); if(p.length) errors.initialPassword=p; } } else if(!Number.isSafeInteger(b.expectedVersion)||b.expectedVersion<=0) errors.expectedVersion=["expectedVersion must be a positive integer."]; return {errors,input:{name,email,role:b.role as UserRole,isActive:b.isActive,initialPassword:b.initialPassword as string|undefined,expectedVersion:b.expectedVersion as number|undefined}}; }
async function cleanupOwner(tx:any,targetId:number,actorId:number){ const tickets=await tx.ticket.findMany({where:{ticketOwnerId:targetId},select:{id:true,version:true}}); for(const ticket of tickets){ await tx.ticketOwnerChange.create({data:{ticketId:ticket.id,previousOwnerId:targetId,nextOwnerId:null,actorId,reason:"ACCOUNT_INELIGIBLE"}}); await tx.ticket.update({where:{id:ticket.id},data:{ticketOwnerId:null,version:{increment:1}}}); } }

export function registerAdminUserRoutes(app:Express, prisma:AdminPrisma){
 app.use("/api/admin",(_req,_res,next)=>next());
 app.get("/api/admin/users",async(req:AuthenticatedRequest,res)=>{ if(!admin(req,res))return; const allowed=new Set(["search","role"]); if(Object.keys(req.query).some(k=>!allowed.has(k)||Array.isArray(req.query[k]))) return fail(res,400,"VALIDATION_FAILED","User query is invalid."); const search=typeof req.query.search==="string"?req.query.search.trim():""; const role=typeof req.query.role==="string"?req.query.role:null; if(search.length>120||(role!==null&&!roles.includes(role as UserRole))) return fail(res,400,"VALIDATION_FAILED","User query is invalid."); try{ const items=await prisma.requesterUser.findMany({where:{...(role?{role:role as UserRole}:{}),...(search?{OR:[{name:{contains:search,mode:"insensitive"}},{email:{contains:search,mode:"insensitive"}}]}:{})},select:adminSelect,orderBy:[{name:"asc"},{id:"asc"}]}); return res.status(200).json({items,applied:{search,role}}); }catch{return fail(res,500,"INTERNAL_ERROR","Unable to complete this request. Please try again.");} });
 app.post("/api/admin/users",async(req:AuthenticatedRequest,res)=>{ if(!admin(req,res)||!requireRequestCsrf(req,res))return; const {errors,input}=validateAccount(req.body,true); if(Object.keys(errors).length||!input) return fail(res,400,"VALIDATION_FAILED","Check the highlighted fields.",errors); try{ const passwordHash=await hashPassword(input.initialPassword!); const user=await prisma.$transaction(async(tx:any)=>{ await lockAdministratorSafety(tx); return tx.requesterUser.create({data:{name:input.name!,email:input.email!,role:input.role,isActive:input.isActive,passwordHash,mustChangePassword:true,passwordChangedAt:null},select:adminSelect}); }); return res.status(201).json({user}); }catch(e){return mapPrisma(e,res);} });
 app.patch("/api/admin/users/:userId",async(req:AuthenticatedRequest,res)=>{ if(!admin(req,res)||!requireRequestCsrf(req,res))return; const userId=positiveId(req.params.userId); if(!userId)return fail(res,400,"VALIDATION_FAILED","User ID is invalid."); const {errors,input}=validateAccount(req.body,false); if(Object.keys(errors).length||!input)return fail(res,400,"VALIDATION_FAILED","Check the highlighted fields.",errors); try{ const actor=req.auth!.user.id; const result=await prisma.$transaction(async(tx:any)=>{ await lockAdministratorSafety(tx); await lockAccountSafety(tx,userId); const current=await tx.requesterUser.findUnique({where:{id:userId},select:{...adminSelect,passwordHash:true}}); if(!current) return null; if(current.version!==input.expectedVersion)throw new Error("VERSION_CONFLICT"); if(userId===actor&&current.role==="ADMINISTRATOR"&&!input.isActive)throw new Error("ADMIN_SELF_DEACTIVATION"); const losesAdmin=current.role==="ADMINISTRATOR"&&current.isActive&&(input.role!=="ADMINISTRATOR"||!input.isActive); if(losesAdmin){ const count=await tx.requesterUser.count({where:{role:"ADMINISTRATOR",isActive:true}}); if(count<=1)throw new Error("LAST_ACTIVE_ADMIN"); }
 const wasEligible=current.isActive&&(current.role==="IT_STAFF"||current.role==="ADMINISTRATOR"); const nextEligible=input.isActive&&(input.role==="IT_STAFF"||input.role==="ADMINISTRATOR"); if(wasEligible&&!nextEligible) await cleanupOwner(tx,userId,actor);
 const updated=await tx.requesterUser.updateMany({where:{id:userId,version:input.expectedVersion},data:{name:input.name!,email:input.email!,role:input.role,isActive:input.isActive,version:{increment:1}}}); if(updated.count!==1)throw new Error("VERSION_CONFLICT"); await tx.session.deleteMany({where:{userId}}); return tx.requesterUser.findUnique({where:{id:userId},select:adminSelect}); }); if(!result)return fail(res,404,"RESOURCE_NOT_FOUND","Resource not found."); const self=userId===req.auth!.user.id; if(self)clearSessionCookie(res,req); return res.status(200).json({user:result,reauthenticationRequired:self}); }catch(e){return mapPrisma(e,res);} });
 app.post("/api/admin/users/:userId/initial-password",async(req:AuthenticatedRequest,res)=>{ if(!admin(req,res)||!requireRequestCsrf(req,res))return; const userId=positiveId(req.params.userId); if(!userId)return fail(res,400,"VALIDATION_FAILED","User ID is invalid."); if(!exactObject(req.body,["initialPassword","expectedVersion"]))return fail(res,400,"VALIDATION_FAILED","Check the highlighted fields."); const b=req.body as any; const errors=typeof b.initialPassword==="string"?validatePasswordInput(b.initialPassword):["Initial password is required."]; if(!Number.isSafeInteger(b.expectedVersion)||b.expectedVersion<=0)errors.push("expectedVersion must be a positive integer."); if(errors.length)return fail(res,400,"VALIDATION_FAILED","Check the highlighted fields.",{initialPassword:errors}); try{ const actor=req.auth!.user.id; const current=await prisma.requesterUser.findUnique({where:{id:userId},select:{passwordHash:true,version:true}}); if(!current)return fail(res,404,"RESOURCE_NOT_FOUND","Resource not found."); if(current.version!==b.expectedVersion)throw new Error("VERSION_CONFLICT"); if(current.passwordHash&&await verifyPassword(b.initialPassword,current.passwordHash))throw new Error("INITIAL_PASSWORD_SAME"); const passwordHash=await hashPassword(b.initialPassword); const result=await prisma.$transaction(async(tx:any)=>{ await lockAccountSafety(tx,userId); const updated=await tx.requesterUser.updateMany({where:{id:userId,version:b.expectedVersion},data:{passwordHash,mustChangePassword:true,passwordChangedAt:null,version:{increment:1}}}); if(updated.count!==1)throw new Error("VERSION_CONFLICT"); await tx.session.deleteMany({where:{userId}}); return tx.requesterUser.findUnique({where:{id:userId},select:adminSelect}); }); const self=userId===actor; if(self)clearSessionCookie(res,req); return res.status(200).json({user:result,reauthenticationRequired:self}); }catch(e){return mapPrisma(e,res);} });
 app.all("/api/admin/users/:userId",(req:Request,res:Response,next)=>{if(["GET","POST","PATCH"].includes(req.method))return next(); res.setHeader("Allow","PATCH"); return fail(res,405,"METHOD_NOT_ALLOWED","Method not allowed.");});
}
